### ISSUE TITLE
[Question] UninstallAplication and Disk Usage

### ISSUE THREAD

**Issue by AjayGhale** [0xFireball/MK.MobileDevice#6]
I write here because i dont find support anywhere else, so im writting a project (personal project) and i already make my app disply info about the device connected via USB, add some other functions like install aplicatiions with a FileDialog, but i want to add the UninstallAplication too and i dont find how to do it someone here have achive this?

**Comment by 0xFireball** [comment]
Hello, it is fine to ask for support here. However, please make sure you are in compliance with GPLv3 when using this library.

Uninstalling applications should be very easy with this library:
Both `iITMDiPhoneLL` and `iPhone` support it.
Just call `UninstallApplication`

Here are the methods in source:

https://github.com/exaphaser/MK.MobileDevice/blob/d68ba61750948f3bf8ef0147e52e2bbb76366a3e/MobileDevice/ITMDiPhoneLL.cs#L324

https://github.com/exaphaser/MK.MobileDevice/blob/ddd8b7ae5e610211efc9f517c622cf9773e96343/MobileDevice/iPhone.cs#L589

`GetApplicationList()` can give you a collection of apps. The `iOSApplication` class has `ApplicationIdentifier`: https://github.com/exaphaser/MK.MobileDevice/blob/d68ba61750948f3bf8ef0147e52e2bbb76366a3e/MobileDevice/iOSApplication.cs#L18

...which gives you the bundleid.

if you need any more help, please ask.

**Comment by AjayGhale** [comment]
hello, thanks for your reply!! 

the iPhone.UninstallAplication now works fine for me, the other thing is that i would like to display the iOS Aplication List on a TextBox or other control on the windows form.. and i dont know how to do this, can you provide some support?

**Comment by 0xFireball** [comment]
Hello, as I mentioned in my above comment,

`GetApplicationList()` will give you a list of `iOSApplication` objects, which you can use to display data. You can use Linq for example to show all the app names:

`string[] appNames = myiPhone.GetApplicationList().Select(app=>app.Name).ToArray()`

**Comment by 0xFireball** [comment]
Also, I'm just curious, I was making a similar app but never finished it; is your project on GitHub? If it is, can you link me?

**Comment by AjayGhale** [comment]
no its not on github but im gonna upload it to dropbox and send you the link what do you say? give me your email can you??

**Comment by 0xFireball** [comment]
Sure, that would be great! But first finish your app.

**Comment by AjayGhale** [comment]
give me your email

**Comment by AjayGhale** [comment]
by the way, did you managed to somehow display the disk usage of an iOS device? can you point me on how ?

**Comment by 0xFireball** [comment]
Yes, you can query `"com.apple.disk_usage" or "com.apple.disk_usage.factory"`.

Use the `RequestProperties(string)` method of `iPhone` with one of the above domains as the parameter.
You should get a property list, and they should contain disk usage information. Unfortunately I don't have any apple devices handy so I can't test this.

You should get an output like this:
```
Disk Usage (Factory)
 AmountDataAvailable: 13519458304
 AmountDataReserved: 209715200
 CalculateDiskUsage: OkilyDokily
 CalendarUsage: 905216
 CameraUsage: 0
 MediaCacheUsage: 4096
 NANDInfo: 
 NotesUsage: 217088
 PhotoUsage: 0
 TotalDataAvailable: 13729173504
 TotalDataCapacity: 29198647296
 TotalDiskCapacity: 31708938240
 TotalSystemAvailable: 335544320
 TotalSystemCapacity: 2510290944
 VoicemailUsage: 0
 WebAppCacheUsage: 0
```
